export const GOVERNOR_CONTRACT = {
  address: "0x6f3E6272A167e8AcCb32072d08E0957F9c79223d" as `0x${string}`,
  abi: [
    {
      inputs: [
        { internalType: "address", name: "timelock_", type: "address" },
        { internalType: "address", name: "nouns_", type: "address" },
        { internalType: "address", name: "vetoer_", type: "address" },
        { internalType: "address", name: "admin_", type: "address" },
        { internalType: "address", name: "implementation_", type: "address" },
        { internalType: "uint256", name: "votingPeriod_", type: "uint256" },
        { internalType: "uint256", name: "votingDelay_", type: "uint256" },
        { internalType: "uint256", name: "proposalThresholdBPS_", type: "uint256" },
        { internalType: "uint256", name: "quorumVotesBPS_", type: "uint256" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [],
      name: "proposalCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "proposalId", type: "uint256" }],
      name: "proposals",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "proposer", type: "address" },
        { internalType: "uint256", name: "eta", type: "uint256" },
        { internalType: "uint256", name: "startBlock", type: "uint256" },
        { internalType: "uint256", name: "endBlock", type: "uint256" },
        { internalType: "uint256", name: "forVotes", type: "uint256" },
        { internalType: "uint256", name: "againstVotes", type: "uint256" },
        { internalType: "uint256", name: "abstainVotes", type: "uint256" },
        { internalType: "bool", name: "canceled", type: "bool" },
        { internalType: "bool", name: "executed", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "proposalId", type: "uint256" }],
      name: "state",
      outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "proposalId", type: "uint256" }],
      name: "getActions",
      outputs: [
        { internalType: "address[]", name: "targets", type: "address[]" },
        { internalType: "uint256[]", name: "values", type: "uint256[]" },
        { internalType: "string[]", name: "signatures", type: "string[]" },
        { internalType: "bytes[]", name: "calldatas", type: "bytes[]" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "blockNumber", type: "uint256" }],
      name: "quorumVotes",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "uint256", name: "id", type: "uint256" },
        { indexed: false, internalType: "address", name: "proposer", type: "address" },
        { indexed: false, internalType: "address[]", name: "targets", type: "address[]" },
        { indexed: false, internalType: "uint256[]", name: "values", type: "uint256[]" },
        { indexed: false, internalType: "string[]", name: "signatures", type: "string[]" },
        { indexed: false, internalType: "bytes[]", name: "calldatas", type: "bytes[]" },
        { indexed: false, internalType: "uint256", name: "startBlock", type: "uint256" },
        { indexed: false, internalType: "uint256", name: "endBlock", type: "uint256" },
        { indexed: false, internalType: "string", name: "description", type: "string" },
      ],
      name: "ProposalCreated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "address", name: "voter", type: "address" },
        { indexed: false, internalType: "uint256", name: "proposalId", type: "uint256" },
        { indexed: false, internalType: "uint8", name: "support", type: "uint8" },
        { indexed: false, internalType: "uint256", name: "votes", type: "uint256" },
        { indexed: false, internalType: "string", name: "reason", type: "string" },
      ],
      name: "VoteCast",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "address", name: "oldAdmin", type: "address" },
        { indexed: false, internalType: "address", name: "newAdmin", type: "address" },
      ],
      name: "NewAdmin",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "address", name: "oldImplementation", type: "address" },
        { indexed: false, internalType: "address", name: "newImplementation", type: "address" },
      ],
      name: "NewImplementation",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "address", name: "oldPendingAdmin", type: "address" },
        { indexed: false, internalType: "address", name: "newPendingAdmin", type: "address" },
      ],
      name: "NewPendingAdmin",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "uint256", name: "oldProposalThresholdBPS", type: "uint256" },
        { indexed: false, internalType: "uint256", name: "newProposalThresholdBPS", type: "uint256" },
      ],
      name: "ProposalThresholdBPSSet",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "uint256", name: "oldQuorumVotesBPS", type: "uint256" },
        { indexed: false, internalType: "uint256", name: "newQuorumVotesBPS", type: "uint256" },
      ],
      name: "QuorumVotesBPSSet",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: "address", name: "oldVetoer", type: "address" },
        { indexed: false, internalType: "address", name: "newVetoer", type: "address" },
      ],
      name: "NewVetoer",
      type: "event",
    },
    {
      inputs: [
        { internalType: "uint256", name: "proposalId", type: "uint256" },
        { internalType: "uint8", name: "support", type: "uint8" },
        { internalType: "string", name: "reason", type: "string" },
        { internalType: "uint32", name: "clientId", type: "uint32" },
      ],
      name: "castRefundableVoteWithReason",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
} as const

export const TREASURY_CONTRACT = {
  address: "0xb1a32FC9F9D8b2cf86C068Cae13108809547ef71" as `0x${string}`,
  abi: [
    {
      inputs: [],
      name: "balance",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
  ],
} as const
